name = "cellular-automata"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-10-10"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsuY2VsbHVsb3NlLnN0dWRpbyQ"
PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL = "/"
PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL = "/"
PUBLIC_POSTHOG_API_KEY = "phc_qizl68Mq6SadcmoO9LEfeqP3Bs6JRVZWvZrHAXHBsu3"
